-define(SIGNATURE, <<"3EAM">>).
-define(SIG_EXPORTS, <<"ExpT">>).
-define(SIG_ATOMS, <<"Atom">>).
-define(SIG_CODE, <<"Code">>).

-define(MARK_FUNCTION, <<255:8>>).
-define(MARK_END_CODE, <<254:8>>).
-define(VAL_X,          1).
-define(VAL_Y,          2).
-define(VAL_ATOM,       3).
-define(VAL_MFARITY,    4).
-define(VAL_INTEGER,    5).
-define(VAL_LIT,        6).

-define(OPCODE_MOVE,        1).
-define(OPCODE_CALL,        2).
-define(OPCODE_TAIL_CALL,   2+128).
-define(OPCODE_APPLY,       3).
-define(OPCODE_TAIL_APPLY,  3+128).
-define(OPCODE_CONS,        4).
-define(OPCODE_RET,         5).
-define(OPCODE_ALLOC,       6).
-define(OPCODE_DEALLOC,     6+128).
